// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"g_battle","status":true,"description":"(v1.0.0)","parameters":{"Actor Color":"0x3366ff"}},
{"name":"rmmz_movement","status":true,"description":"(v1.0.0)","parameters":{}}
];
